language: ruby
rvm:
- 2.2.5
- 2.3.1
before_install: gem install bundler -v 1.10.6
deploy:
  provider: rubygems
  on:
    tags: true
  api_key:
    secure: E4iOts6aVaN7qavJ39NKoAhtJPXVqXG0XQIXbJKshacxzs9WdZxB8v9lxCNCq9nAaybzw++e/CybT3jv+OeujMMJRF61qQ6LxD5btBJlrMItB1RIU0Gb6I0xjb/iIZk5hQejYxxi1wSezUBwwxP+AtyaY5Dw8CB/hH+jk8EgZwWpb70fpK6IARrZNM5XpoEIB/f/ZF1JU6Mfcdvik4mG6sbqTz/3bjv6QbzDw80ejIjzlFeAx7hek4XuIV5KAHU2+ArpRuMIpm03yOBgqrMke481Zqhu6XATz/SV9MLzpVgehttxziTj9fNEkW8Lfn35s4+CxNK1f+UHRraTBXFaiHCCclKAt8NmaxnaCSzHziYzRrryY0tHICiyirdftt6exFf3a+RUECEQim/BrOq7b3T1qMDewtWOp6zH2An+QQ/mVfcx/SPuzkrkZ1zU+MkZhQmJWCgbJQT7P4aeJLUhE9oi37PZg2Kurv5Ul0ERpjVfV0Y102IegfHlp8S/67oDeeQJmh9vhd22EhVnwWYnKxlnEsCFJeaclKtNfCb6VIoyzXmpRdwJyNzMvgHv5WnATQXBhzWXAssaZyEF2FLj88/vHByjJodFfTg3YS2Vj1DbozeLbySXr21+VxHiF0xclsCseQLtogiXkUCcfbHlBe3dCK3VPUVOgA1g0FDI6sE=
notifications:
  slack:
    secure: I1CCQzA99RbTG/urNV+zB/fH2H6o8SiMmr4WlXmJKHDJEdVwiFmEGLy0Hch1V2Me6udT3FW8uBMshVz2oVhCpu+vuGcky5raf9moHxM3go7kocFPET+NFBexJ0ejNZn+/P9VhFokafYR27AJyTU5TRR7gysnVqmw3kJBC66JyQRaly2zsL2cxkTtCAseArnou0e1K9SqKi8vQAT24nk7Vqxl9LcnCFjGuzNjjVA39SLRa2OSA9O2TOC/nQwSqQCMc0CiOd2qDD9PHC49uSvMnNjVRU5FLHUu3muBEY2ytSVlN1kQZRd4cdYEM4JXcfyEABrH/JggdastlSOAHDjJEarq9vNdaOBoNgiKqH1hF0yW/niv8+0ux0yRfdNEw6543U3KB5YWAlEtlm0cB5HJAx3urZxask2gHyApFOGjASItxDnPH9Z8S9HTTnUEy51oY1ELXUvANXdkRHI0ACGHeBaM3Pnm5//QpUT+V0jYo82yTe8j8H8O+w8eMQ86LEZ1I8hB+H8hqS3BLU3NiVa0MPpGwOfsbpNIOlUP61LS1dcTchAdMxZHeHp+d8gmzAlJCeesZeb+zv6kmu2iN+/ESsT0CT9Bq0TGyK3C+87y7vmB1k+qibnFt11/IAm/r23fYU6ctDTDY2Z/h4uDpN7Fycqeh4xfYqsmQKuEs66aZY0=
